

#GENERAL SERVICE INFO
service: DAT250-Auction
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-2
  environment:
    AUCTION_TABLE: "${opt:stage, self:provider.stage}-Auctions"
    SELLER_TABLE: "${opt:stage, self:provider.stage}-Sellers"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

# LAMBDA FUNCTIONS
functions:
  createAuction:
    handler: api/auctions/create.create
    memorySize: 128
    events:
      - http:
          path: createAuction
          method: post
  getAuction:
    handler: api/auctions/get.get
    events:
      - http:
          path: getAuction
          method: get
  bidOnAuction:
    handler: api/auctions/bid.bid
    events:
      - http:
          path: postBid
          method: post
  updateAuction:
    handler: api/auctions/update.update
    events:
      - http:
          path: updateEvent
          method: post
  createSeller:
    handler: api/sellers/create.create
    events:
      - http:
          path: createSeller
          method: post
  getSeller:
    handler: api/sellers/get.get
    events:
      - http:
          path: getSeller
          method: get
  getSellerBids:
    handler: api/sellers/bids.bids
    events:
      - http:
          path: getBids
          method: get
  editSeller:
    handler: api/sellers/edit.edit
    events:
      - http:
          path: editSeller
          method: post
  deleteSeller:
    handler: api/sellers/delete.delete
    events:
      - http:
          path: deleteSeller
          method: delete

# RESROUCES
resources:
  Resources:
    AuctionsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "uuid"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "uuid"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: "${self:provider.environment.AUCTION_TABLE}"
    SellersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "uuid"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "uuid"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: "${self:provider.environment.SELLER_TABLE}"

# EXTRA PLUGINS
plugins:
  - serverless-offline
